[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.install]
cmds = ["cd backend && mvn clean install -DskipTests"]

[start]
cmd = "cd backend && java -jar target/student-management-system-1.0.0.jar"

